### ISSUE TITLE
Logprior

### ISSUE THREAD

**Issue by pharringtonp19** [jeremiecoullon/jax_MCMC_blog_post#2]
Could you expand upon how you defined the log prior in your code?

```
def log_prior(theta):
    return -(0.5/10)*jnp.dot(theta,theta)
```
I am just learning about this topic/material so I wanted to check that I am understanding things correctly. The above function looks like it returns is the log prior minus some constant that doesn't depend on the parameters. Is that correct? If that's true, should the scalar multiple be `-0.5` or am I confused here? -- Thanks

**Comment by jeremiecoullon** [comment]
Thanks for your questions!

The prior is a Gaussian with a diagonal covariance matrix (and each diagonal element is 10). So each parameter has variance 10. The -0.5 is the term in the [Gaussian pdf](https://en.wikipedia.org/wiki/Multivariate_normal_distribution#Non-degenerate_case) and the 10 is the variance. This is why I put 0.5/10.

About the log-prior minus a constant: that's correct, but I would think about it slightly differently. The log-prior is indeed actually this inner product + some constant (you can calculate the constant which involves the covariance matrix: see the [equation for the density](https://en.wikipedia.org/wiki/Multivariate_normal_distribution#Non-degenerate_case)). However as the second bit doesn't depend on parameters (and so will not make a difference in MCMC) we simply ignore and call this inner product the "log-prior" instead. 

Does this answer your questions?

**Comment by pharringtonp19** [comment]
@jeremiecoullon Absolutely, I missed the fact that the diagonal of the covariance matrix was `10`!

I'll probably continue to post questions if that's okay. Really enjoying your blog and your [library](https://github.com/jeremiecoullon/SGMCMCJax)

**Comment by jeremiecoullon** [comment]
Great! Ask if you have more questions :)
